// ============================================================
// Cloudinary URL construction — PURE, and deliberately SDK-free.
//
// Split out from the storage adapter for one concrete reason: the adapter
// imports the Cloudinary Node SDK, which requires `fs`. These helpers are used
// by the next/image loader, which runs in the BROWSER, and by src/lib/cms/media.ts,
// which is imported by client components — so importing them from the adapter
// dragged the whole Node SDK into the client bundle and failed the build.
//
// Nothing here talks to Cloudinary. It is all string manipulation against a
// URL shape, which is also why it is cheap to test (npm run test:cloudinary).
// ============================================================

const VIDEO_EXTENSIONS = new Set(['mp4', 'webm', 'mov', 'm4v'])
const RAW_EXTENSIONS = new Set(['pdf', 'glb', 'gltf', 'zip', 'csv', 'txt', 'doc', 'docx'])

export type CloudinaryResourceType = 'image' | 'raw' | 'video'

const extensionOf = (filename: string) => filename.split('.').pop()?.toLowerCase() ?? ''

/**
 * Which Cloudinary storage class a file belongs to.
 *
 * Derived from the FILENAME, not the mimetype, because `generateURL` is given
 * nothing but a filename and its answer has to match what `handleUpload` chose.
 * If the two disagree, every URL points at a file that is not there.
 *
 * PDFs and `.glb` models go to `raw`. Cloudinary can treat a PDF as an image and
 * transform it, but these are downloads — a technical report and a CAD model —
 * and `raw` delivers the bytes exactly as uploaded.
 */
export function resourceTypeFor(filename: string): CloudinaryResourceType {
  const ext = extensionOf(filename)
  if (VIDEO_EXTENSIONS.has(ext)) return 'video'
  if (RAW_EXTENSIONS.has(ext)) return 'raw'
  return 'image'
}

/**
 * The Cloudinary public id for a stored file.
 *
 * Raw files keep their extension; images and video do not — Cloudinary stores
 * the format alongside the id for those. Getting this backwards produces
 * `photo.jpg.jpg`, which Cloudinary will happily 404 on.
 */
export function publicIdFor(
  folder: string,
  filename: string,
  type: CloudinaryResourceType
): string {
  const base = type === 'raw' ? filename : filename.replace(/\.[^.]+$/, '')
  return folder ? `${folder}/${base}` : base
}

// ── Delivery URLs ─────────────────────────────────────────────

/**
 * Insert a transformation into a Cloudinary delivery URL.
 *
 * This is what replaces Sanity's `urlFor(img).width(440).height(550)`. The
 * migration to Payload lost on-the-fly resizing and worked around it with four
 * fixed sizes generated by sharp at upload; Cloudinary does it properly, so any
 * size is one URL away and nothing has to be generated in advance.
 *
 * A Cloudinary URL is `…/upload/<transformations>/<version>/<public_id>`, so the
 * transformation goes immediately after `/upload/` — before the version segment,
 * which is why this splices rather than concatenates.
 *
 * Returns anything that is not a Cloudinary URL untouched. That is load-bearing:
 * the same helper runs against local-disk URLs when Cloudinary is not
 * configured, and against the site's own `/logo.svg`.
 */
export function cldTransform(url: string | null | undefined, transform: string): string | null {
  if (!url) return null
  const marker = '/upload/'
  const at = url.indexOf(marker)
  if (at === -1 || !url.includes('res.cloudinary.com')) return url
  return `${url.slice(0, at + marker.length)}${transform}/${url.slice(at + marker.length)}`
}

export interface CldOptions {
  width?: number
  height?: number
  /** `fill` crops to the exact box; `limit` fits inside it and never upscales. */
  crop?: 'fill' | 'limit' | 'fit'
  quality?: number | 'auto'
}

/**
 * Build the transformation string.
 *
 * `f_auto` negotiates AVIF or WebP against the browser, and `q_auto` picks a
 * quality per image rather than per site — together they are most of the reason
 * to put images on Cloudinary at all.
 *
 * `g_auto` only applies when cropping to a fixed box, and it is what replaces
 * the focal point that used to be set by hand: Cloudinary picks the region of
 * interest itself, which is both better than a default centre crop and one less
 * thing for an editor to remember.
 */
export function cldParams({ width, height, crop = 'limit', quality = 'auto' }: CldOptions): string {
  const parts = ['f_auto', `q_${quality}`]
  if (width) parts.push(`w_${width}`)
  if (height) parts.push(`h_${height}`)
  if (width && height) parts.push(`c_${crop === 'limit' ? 'fill' : crop}`, 'g_auto')
  else if (width || height) parts.push(`c_${crop}`)
  return parts.join(',')
}
