/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    announcements: Announcement;
    posts: Post;
    research: Research;
    sponsors: Sponsor;
    members: Member;
    testimonials: Testimonial;
    rovers: Rover;
    competitions: Competition;
    'sar-videos': SarVideo;
    products: Product;
    'product-categories': ProductCategory;
    orders: Order;
    donations: Donation;
    applications: Application;
    media: Media;
    documents: Document;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    research: ResearchSelect<false> | ResearchSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    rovers: RoversSelect<false> | RoversSelect<true>;
    competitions: CompetitionsSelect<false> | CompetitionsSelect<true>;
    'sar-videos': SarVideosSelect<false> | SarVideosSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    recruitment: Recruitment;
    crowdfunding: Crowdfunding;
    shop: Shop;
  };
  globalsSelect: {
    recruitment: RecruitmentSelect<false> | RecruitmentSelect<true>;
    crowdfunding: CrowdfundingSelect<false> | CrowdfundingSelect<true>;
    shop: ShopSelect<false> | ShopSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The strip across the top of every page. Only active, in-window rows show.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: string;
  /**
   * Internal label so you can tell rows apart. Never shown on the site.
   */
  title: string;
  /**
   * What visitors read. One short sentence — it has to fit on a phone.
   */
  message: string;
  /**
   * Optional. Makes the bar clickable.
   */
  link?: string | null;
  /**
   * The call to action, e.g. "Apply Now", "See Results".
   */
  linkLabel?: string | null;
  /**
   * Leave empty to start immediately.
   */
  startDate?: string | null;
  /**
   * Leave empty to run until switched off by hand.
   */
  endDate?: string | null;
  isActive?: boolean | null;
  /**
   * Lower numbers are shown first.
   */
  priority?: number | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everything on /news.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  /**
   * The URL for this page. Generated from the name if left empty. Changing it breaks any link already shared.
   */
  slug: string;
  title: string;
  publishedAt?: string | null;
  category: 'competition-update' | 'rover-reveal' | 'research-highlight' | 'outreach' | 'team-news';
  author?: (string | null) | Member;
  featuredImage?: (string | null) | Media;
  /**
   * The summary on cards and in link previews. Written to stand alone — it is often all anyone reads.
   */
  excerpt: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everyone who has worked on the team, current and alumni.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  /**
   * The URL for this page. Generated from the name if left empty. Changing it breaks any link already shared.
   */
  slug: string;
  name: string;
  /**
   * A square-ish headshot reads best.
   */
  photo?: (string | null) | Media;
  role?: string | null;
  /**
   * One short line under the name, e.g. "Autonomy & perception, building rovers that think."
   */
  tagline?: string | null;
  /**
   * Drives the badge colour and the filter on /team.
   */
  subTeam?:
    | ('uav' | 'rnd' | 'autonomous' | 'controls' | 'mechanical' | 'electronics' | 'science' | 'network' | 'management')
    | null;
  yearOfStudy?: string | null;
  joinedYear?: number | null;
  graduationYear?: number | null;
  /**
   * Every year this member was active, e.g. 2021, 2022, 2023. Drives the contribution timeline on their profile.
   */
  yearsContributed?: number[] | null;
  isAlumni?: boolean | null;
  /**
   * Where they work or study now.
   */
  currentOrg?: string | null;
  isActive?: boolean | null;
  /**
   * A few sentences on who they are and what they do here.
   */
  bio?: string | null;
  quote?: string | null;
  /**
   * What they specialise in — "Path planning", "PCB design", "Structural FEA".
   */
  focusAreas?: string[] | null;
  skills?: string[] | null;
  achievements?:
    | {
        /**
         * The award, role or milestone, e.g. "URC 2023 — 5th Worldwide".
         */
        title: string;
        year?: number | null;
        /**
         * One-line summary of what they achieved.
         */
        achievement?: string | null;
        /**
         * Optional bullet points elaborating on it.
         */
        details?: string[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Notable projects, repos or publications — a name and a link.
   */
  works?:
    | {
        name: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  linkedin?: string | null;
  github?: string | null;
  website?: string | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for screen readers and for when it fails to load. Not a caption — say what is in it.
   */
  alt: string;
  /**
   * Optional. Shown under the image in galleries. Sanity stored this on each usage; here it lives with the image, so one edit fixes it everywhere.
   */
  caption?: string | null;
  /**
   * Photographer or source, where one needs crediting.
   */
  credit?: string | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Publications. Authors are team members, so profiles list them automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research".
 */
export interface Research {
  id: string;
  /**
   * The URL for this page. Generated from the name if left empty. Changing it breaks any link already shared.
   */
  slug: string;
  title: string;
  /**
   * In citation order. Each author’s profile links back to this paper.
   */
  authors?: (string | Member)[] | null;
  year: number;
  status: 'published' | 'preprint' | 'under-review';
  conference?: string | null;
  abstract: string;
  doi?: string | null;
  pdfFile?: (string | null) | Document;
  /**
   * Drives the filter on /research.
   */
  topics?: string[] | null;
  citation?: string | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  /**
   * What this file is, in words a person would search for — e.g. "Taurus SAR report 2024". Used as the download link label.
   */
  title: string;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Shown on /sponsors and in the strip across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: string;
  name: string;
  tier: 'title' | 'gold' | 'silver' | 'bronze' | 'in-kind';
  /**
   * The dark-mark version, which reads on white backgrounds.
   */
  logoLight?: (string | null) | Media;
  /**
   * The light-mark version, which reads on dark backgrounds.
   */
  logoDark?: (string | null) | Media;
  /**
   * Fallback for older entries. Prefer the two theme-specific logos above.
   */
  logo?: (string | null) | Media;
  website?: string | null;
  startYear?: number | null;
  isActive?: boolean | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Only featured testimonials are shown on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  role?: string | null;
  organization?: string | null;
  /**
   * Keep it punchy — one to three sentences.
   */
  quote: string;
  /**
   * A square-ish headshot reads best.
   */
  photo?: (string | null) | Media;
  /**
   * LinkedIn, faculty page or personal site. Makes the name clickable.
   */
  link?: string | null;
  /**
   * Off means invisible. Tick to publish it to Home and About.
   */
  featured?: boolean | null;
  /**
   * Lower shows first. Ties fall back to name.
   */
  order?: number | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The fleet. Mark exactly one as the current flagship.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rovers".
 */
export interface Rover {
  id: string;
  /**
   * The URL for this page. Generated from the name if left empty. Changing it breaks any link already shared.
   */
  slug: string;
  /**
   * The codename, e.g. "Taurus", "Hypersonic".
   */
  name: string;
  year: number;
  /**
   * The team’s current rover. Highlighted across the site.
   */
  isFlagship?: boolean | null;
  /**
   * A short product-style line, e.g. "The rover that learned to think on Martian terrain."
   */
  tagline?: string | null;
  /**
   * Two to four sentences on this rover and what made the build notable. Shown in the hero.
   */
  overview?: string | null;
  /**
   * Lead engineer for this build cycle.
   */
  teamLead?: string | null;
  /**
   * The competition this rover was built for, e.g. URC 2026.
   */
  competition?: (string | null) | Competition;
  /**
   * System Acceptance Review video. Paste the full watch or youtu.be link — it is embedded on the page.
   */
  sarVideoUrl?: string | null;
  /**
   * The hero shot. Falls back to the first gallery image when empty.
   */
  featuredImage?: (string | null) | Media;
  /**
   * Captions live on the image itself now (Media → Caption), so fixing one fixes it everywhere it appears.
   */
  gallery?: (string | Media)[] | null;
  diagrams?: (string | Media)[] | null;
  /**
   * Hotspots overlaid on the first diagram, positioned by percentage.
   */
  diagramAnnotations?:
    | {
        label: string;
        description?: string | null;
        xPercent: number;
        yPercent: number;
        id?: string | null;
      }[]
    | null;
  cadModel?: (string | null) | Document;
  technicalPdf?: (string | null) | Document;
  /**
   * The structured specs shown on the fleet cards.
   */
  specs?: {
    weight?: string | null;
    dimensions?: string | null;
    driveSystem?: string | null;
    payload?: string | null;
    dof?: number | null;
    autonomy?: string | null;
  };
  /**
   * Free-form telemetry for the detail page, e.g. "Comms Range" → "3.3 km NLoS".
   */
  keySpecs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Notable named hardware and software — "Jetson Orin", "ZED 2i", "ROS2 Humble", "YOLO11n".
   */
  namedComponents?: string[] | null;
  /**
   * The headline breakthroughs. Drives the feature reel on the page.
   */
  keyInnovations?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Mechanical, Controls & Software, Electronics, Network & Vision, Autonomy, Science. Each becomes a feature section.
   */
  subsystems?:
    | {
        name: string;
        /**
         * Colours the section accent and links it to a sub-team.
         */
        subTeam?:
          | (
              | 'uav'
              | 'rnd'
              | 'autonomous'
              | 'controls'
              | 'mechanical'
              | 'electronics'
              | 'science'
              | 'network'
              | 'management'
            )
          | null;
        summary: string;
        /**
         * Concrete bullets — named parts, numbers, techniques.
         */
        highlights?: string[] | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * How this rover tackles each competition mission — Delivery, Equipment Servicing, Autonomous Navigation, Science.
   */
  missions?:
    | {
        name: string;
        summary: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Who built this rover. Their sub-team drives the tab filter on the page.
   */
  crew?:
    | {
        member: string | Member;
        /**
         * What they worked on here, e.g. "Lead — manipulator & IK".
         */
        contribution?: string | null;
        /**
         * Only if their contribution to THIS rover differs from their primary sub-team. Otherwise the member’s own sub-team is used.
         */
        subTeamOverride?:
          | (
              | 'uav'
              | 'rnd'
              | 'autonomous'
              | 'controls'
              | 'mechanical'
              | 'electronics'
              | 'science'
              | 'network'
              | 'management'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every competition the team has entered, with its result and roster.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions".
 */
export interface Competition {
  id: string;
  /**
   * The URL for this page. Generated from the name if left empty. Changing it breaks any link already shared.
   */
  slug: string;
  name: string;
  shortName: string;
  year: number;
  location?: string | null;
  result?: string | null;
  rank?: number | null;
  totalTeams?: number | null;
  rover?: (string | null) | Rover;
  teamMembers?:
    | {
        member: string | Member;
        competitionRole?:
          | (
              | 'Driver'
              | 'Science Lead'
              | 'Systems Integrator'
              | 'Operator'
              | 'Arm Operator'
              | 'Autonomy Lead'
              | 'Team Lead'
              | 'Support'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  sarVideo?: string | null;
  gallery?: (string | Media)[] | null;
  reportPdf?: (string | null) | Document;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sar-videos".
 */
export interface SarVideo {
  id: string;
  title: string;
  competition: string | Competition;
  year: number;
  youtubeUrl: string;
  /**
   * Optional — YouTube’s own thumbnail is used when empty.
   */
  thumbnail?: (string | null) | Media;
  description?: string | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The catalogue. Stock lives on each variant and moves by itself as orders come in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * The /shop/… URL. Changing it breaks any link already shared.
   */
  slug: string;
  title: string;
  category: string | ProductCategory;
  /**
   * One line under the name on the product card.
   */
  tagline?: string | null;
  /**
   * Whole taka — this shop has no minor unit.
   */
  basePrice: number;
  /**
   * Optional. Shown struck through, so it must be HIGHER than the price.
   */
  compareAtPrice?: number | null;
  /**
   * The first image is used on cards and in the order email.
   */
  images: (string | Media)[];
  /**
   * What the picker is called on the product page — "Size", "Colour", "Option".
   */
  variantAxisLabel?: string | null;
  /**
   * On: the shop refuses to oversell and stock counts down with each order. Off: unlimited — for made-to-order or pre-order items.
   */
  trackInventory?: boolean | null;
  /**
   * Every product has at least one. A product with no real options keeps the single "Standard" row — that is what holds its stock.
   */
  variants: {
    /**
     * What the customer picks, e.g. "M". Two axes can be one label: "M / Black".
     */
    label: string;
    /**
     * Optional. Printed on the invoice when set.
     */
    sku?: string | null;
    /**
     * Moves by itself as orders are placed and cancelled. Edit only to record a real physical recount.
     */
    stock: number;
    /**
     * Flagged in Shop → Low Stock at or below this.
     */
    lowStockThreshold?: number | null;
    /**
     * Only if this variant costs more than the base price. Empty = product price.
     */
    priceOverride?: number | null;
    /**
     * Turn off to hide this variant without deleting it. Deleting a row orphans the stock accounting of any order that bought it.
     */
    isActive?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Optional cap for this product on top of the shop-wide limit. For scarce items.
   */
  maxPerOrder?: number | null;
  /**
   * The main product copy. Materials, fit, what it is.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown in an accordion. Plain text — one measurement per line reads best.
   */
  sizeGuide?: string | null;
  careInfo?: string | null;
  /**
   * Off withdraws it from sale. Existing orders keep their own copy of the details, so order history does not change.
   */
  isActive?: boolean | null;
  /**
   * Featured products lead the shop grid and appear in the homepage teaser.
   */
  featured?: boolean | null;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: string;
  /**
   * Used in the /shop filter URL. Changing it breaks existing links.
   */
  slug: string;
  title: string;
  /**
   * Optional one-liner under the category heading.
   */
  description?: string | null;
  /**
   * Lower numbers come first in the filter bar.
   */
  order?: number | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Work the queue oldest-first. Changing the status emails the customer once; cancelling returns the stock.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Changing this emails the customer — once per status, however many times you save. Cancelling returns the reserved stock to inventory.
   */
  status: 'placed' | 'confirmed' | 'processing' | 'dispatched' | 'delivered' | 'cancelled';
  /**
   * Cash on delivery — mark Paid once the money is actually in hand.
   */
  paymentStatus: 'unpaid' | 'paid' | 'refunded';
  /**
   * Included in the cancellation email, so write it for the customer to read.
   */
  cancellationReason?: string | null;
  /**
   * Tick and save to send the order confirmation again — use when Email Status shows failed or skipped. Clears itself once sent.
   */
  resendEmail?: boolean | null;
  /**
   * NEVER PUBLISHED and never emailed. Courier reference, who packed it, anything.
   */
  adminNotes?: string | null;
  customerName: string;
  /**
   * NEVER PUBLISHED. Where every order email goes.
   */
  customerEmail: string;
  /**
   * NEVER PUBLISHED — not even partially. See “Phone — last 3”.
   */
  customerPhone: string;
  /**
   * Computed once, when the order is placed. The track page shows this so the buyer can confirm the order is theirs — which is what lets the public read avoid selecting customerPhone at all. Masking in React would be too late: the raw value would already have crossed into the page.
   */
  phoneLast3?: string | null;
  deliveryMethod: 'standard' | 'campus';
  /**
   * NEVER PUBLISHED. Home delivery only — empty for campus handover.
   */
  deliveryAddress?: {
    line1?: string | null;
    line2?: string | null;
    area?: string | null;
    city?: string | null;
    postcode?: string | null;
  };
  campusDetails?: {
    handoverPoint?: string | null;
    bracuId?: string | null;
  };
  /**
   * Anything they typed at checkout — landmarks, timing, sizing worries.
   */
  customerNote?: string | null;
  /**
   * A snapshot taken when the order was placed. Renaming, repricing or deleting a product never changes what is recorded here.
   */
  items: {
    productTitle?: string | null;
    variantLabel?: string | null;
    sku?: string | null;
    quantity?: number | null;
    unitPrice?: number | null;
    lineTotal?: number | null;
    productId?: string | null;
    variantKey?: string | null;
    productSlug?: string | null;
    imageUrl?: string | null;
    /**
     * Whether this line came off the shelf when the order was placed. Recorded per line because a cancellation must return exactly what was taken — if inventory tracking is switched on or off in between, asking the product what it does NOW would either strand the units or invent stock that never existed.
     */
    stockTaken?: boolean | null;
    id?: string | null;
  }[];
  subtotal: number;
  /**
   * Always 0 for campus handover.
   */
  deliveryFee: number;
  /**
   * What the customer pays on delivery. It has been invoiced.
   */
  total: number;
  /**
   * What the customer types into /shop/track.
   */
  trackId: string;
  placedAt: string;
  paymentMethod?: string | null;
  /**
   * Appended automatically each time the status changes.
   */
  statusHistory?:
    | {
        status?: string | null;
        at?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Guarantees one email per status. Saving the order five times cannot send five emails.
   */
  notifiedStatuses?: string[] | null;
  /**
   * If this is not “Sent”, tick “Re-send the confirmation email”.
   */
  emailStatus?: ('sent' | 'failed' | 'skipped') | null;
  /**
   * True once the order has taken its units out of inventory.
   */
  stockReserved?: boolean | null;
  /**
   * Set when a cancellation put the units back. Its presence is what stops a repeated hook restoring the same stock twice.
   */
  stockRestoredAt?: string | null;
  /**
   * Sent by the checkout form. Stops a double-click or a retried request creating two orders.
   */
  idempotencyKey?: string | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The verification queue. A donation is invisible on the site until it is approved, and its amount is never shown at all.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: string;
  status: 'pending' | 'approved' | 'rejected';
  /**
   * NEVER PUBLISHED. Sets this donor’s position on the public roll — the roll shows the rank, never the figure. Required to approve.
   */
  amount?: number | null;
  /**
   * Shown publicly as the verified date, and breaks ties between equal amounts.
   */
  approvedAt?: string | null;
  /**
   * Who checked the statement. Internal only.
   */
  verifiedBy?: string | null;
  /**
   * Never shown publicly. Use it when replying to the donor by hand.
   */
  rejectionReason?: string | null;
  /**
   * Never shown publicly.
   */
  adminNotes?: string | null;
  paymentMethod?: ('bKash' | 'Nagad' | 'Rocket' | 'Upay' | 'Bank Transfer' | 'Other') | null;
  donatedAt?: string | null;
  /**
   * NEVER PUBLISHED. Match this against the statement.
   */
  senderAccount?: string | null;
  /**
   * NEVER PUBLISHED. The fastest way to confirm a transfer.
   */
  transactionId?: string | null;
  /**
   * NEVER PUBLISHED.
   */
  contactEmail?: string | null;
  /**
   * NEVER PUBLISHED.
   */
  contactPhone?: string | null;
  /**
   * Always recorded so payments can be matched. Replaced by “Anonymous” in the public roll when the donor asked to stay anonymous — the real name is never sent to a browser.
   */
  donorName?: string | null;
  /**
   * The donor’s choice.
   */
  isAnonymous?: boolean | null;
  /**
   * e.g. “BRACU CSE ’22”. Suppressed publicly when anonymous.
   */
  affiliation?: string | null;
  /**
   * Shown on the supporters roll. Editable — trim anything unsuitable before approving.
   */
  message?: string | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from /join/apply. Never shown on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: string;
  status?: ('new' | 'shortlisted' | 'interview' | 'accepted' | 'rejected') | null;
  /**
   * Never visible to the applicant.
   */
  reviewerNotes?: string | null;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  studentId?: string | null;
  year?: string | null;
  department?: string | null;
  subteam1?:
    | (
        | 'Mechanical & CAD'
        | 'Electronics'
        | 'Controls & Software'
        | 'Network & Vision'
        | 'AI & Autonomous'
        | 'Astrobio & Science'
        | 'Unmanned Aerial Vehicles'
        | 'Management & Outreach'
        | 'Research & Documentation'
      )
    | null;
  subteam2?:
    | (
        | 'Mechanical & CAD'
        | 'Electronics'
        | 'Controls & Software'
        | 'Network & Vision'
        | 'AI & Autonomous'
        | 'Astrobio & Science'
        | 'Unmanned Aerial Vehicles'
        | 'Management & Outreach'
        | 'Research & Documentation'
      )
    | null;
  whyJoin?: string | null;
  experience?: string | null;
  portfolio?: string | null;
  submittedAt?: string | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Shown in the admin UI so changes are attributable to a person.
   */
  name: string;
  role: 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'announcements';
        value: string | Announcement;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'research';
        value: string | Research;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: string | Sponsor;
      } | null)
    | ({
        relationTo: 'members';
        value: string | Member;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'rovers';
        value: string | Rover;
      } | null)
    | ({
        relationTo: 'competitions';
        value: string | Competition;
      } | null)
    | ({
        relationTo: 'sar-videos';
        value: string | SarVideo;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: string | ProductCategory;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'donations';
        value: string | Donation;
      } | null)
    | ({
        relationTo: 'applications';
        value: string | Application;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  link?: T;
  linkLabel?: T;
  startDate?: T;
  endDate?: T;
  isActive?: T;
  priority?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  publishedAt?: T;
  category?: T;
  author?: T;
  featuredImage?: T;
  excerpt?: T;
  body?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_select".
 */
export interface ResearchSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  authors?: T;
  year?: T;
  status?: T;
  conference?: T;
  abstract?: T;
  doi?: T;
  pdfFile?: T;
  topics?: T;
  citation?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  tier?: T;
  logoLight?: T;
  logoDark?: T;
  logo?: T;
  website?: T;
  startYear?: T;
  isActive?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  photo?: T;
  role?: T;
  tagline?: T;
  subTeam?: T;
  yearOfStudy?: T;
  joinedYear?: T;
  graduationYear?: T;
  yearsContributed?: T;
  isAlumni?: T;
  currentOrg?: T;
  isActive?: T;
  bio?: T;
  quote?: T;
  focusAreas?: T;
  skills?: T;
  achievements?:
    | T
    | {
        title?: T;
        year?: T;
        achievement?: T;
        details?: T;
        id?: T;
      };
  works?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  linkedin?: T;
  github?: T;
  website?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  organization?: T;
  quote?: T;
  photo?: T;
  link?: T;
  featured?: T;
  order?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rovers_select".
 */
export interface RoversSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  year?: T;
  isFlagship?: T;
  tagline?: T;
  overview?: T;
  teamLead?: T;
  competition?: T;
  sarVideoUrl?: T;
  featuredImage?: T;
  gallery?: T;
  diagrams?: T;
  diagramAnnotations?:
    | T
    | {
        label?: T;
        description?: T;
        xPercent?: T;
        yPercent?: T;
        id?: T;
      };
  cadModel?: T;
  technicalPdf?: T;
  specs?:
    | T
    | {
        weight?: T;
        dimensions?: T;
        driveSystem?: T;
        payload?: T;
        dof?: T;
        autonomy?: T;
      };
  keySpecs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  namedComponents?: T;
  keyInnovations?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  subsystems?:
    | T
    | {
        name?: T;
        subTeam?: T;
        summary?: T;
        highlights?: T;
        image?: T;
        id?: T;
      };
  missions?:
    | T
    | {
        name?: T;
        summary?: T;
        id?: T;
      };
  crew?:
    | T
    | {
        member?: T;
        contribution?: T;
        subTeamOverride?: T;
        id?: T;
      };
  description?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions_select".
 */
export interface CompetitionsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  shortName?: T;
  year?: T;
  location?: T;
  result?: T;
  rank?: T;
  totalTeams?: T;
  rover?: T;
  teamMembers?:
    | T
    | {
        member?: T;
        competitionRole?: T;
        id?: T;
      };
  sarVideo?: T;
  gallery?: T;
  reportPdf?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sar-videos_select".
 */
export interface SarVideosSelect<T extends boolean = true> {
  title?: T;
  competition?: T;
  year?: T;
  youtubeUrl?: T;
  thumbnail?: T;
  description?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  tagline?: T;
  basePrice?: T;
  compareAtPrice?: T;
  images?: T;
  variantAxisLabel?: T;
  trackInventory?: T;
  variants?:
    | T
    | {
        label?: T;
        sku?: T;
        stock?: T;
        lowStockThreshold?: T;
        priceOverride?: T;
        isActive?: T;
        id?: T;
      };
  maxPerOrder?: T;
  description?: T;
  sizeGuide?: T;
  careInfo?: T;
  isActive?: T;
  featured?: T;
  order?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  order?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  status?: T;
  paymentStatus?: T;
  cancellationReason?: T;
  resendEmail?: T;
  adminNotes?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  phoneLast3?: T;
  deliveryMethod?: T;
  deliveryAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        area?: T;
        city?: T;
        postcode?: T;
      };
  campusDetails?:
    | T
    | {
        handoverPoint?: T;
        bracuId?: T;
      };
  customerNote?: T;
  items?:
    | T
    | {
        productTitle?: T;
        variantLabel?: T;
        sku?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        productId?: T;
        variantKey?: T;
        productSlug?: T;
        imageUrl?: T;
        stockTaken?: T;
        id?: T;
      };
  subtotal?: T;
  deliveryFee?: T;
  total?: T;
  trackId?: T;
  placedAt?: T;
  paymentMethod?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        at?: T;
        note?: T;
        id?: T;
      };
  notifiedStatuses?: T;
  emailStatus?: T;
  stockReserved?: T;
  stockRestoredAt?: T;
  idempotencyKey?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  status?: T;
  amount?: T;
  approvedAt?: T;
  verifiedBy?: T;
  rejectionReason?: T;
  adminNotes?: T;
  paymentMethod?: T;
  donatedAt?: T;
  senderAccount?: T;
  transactionId?: T;
  contactEmail?: T;
  contactPhone?: T;
  donorName?: T;
  isAnonymous?: T;
  affiliation?: T;
  message?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  status?: T;
  reviewerNotes?: T;
  name?: T;
  email?: T;
  phone?: T;
  studentId?: T;
  year?: T;
  department?: T;
  subteam1?: T;
  subteam2?: T;
  whyJoin?: T;
  experience?: T;
  portfolio?: T;
  submittedAt?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Controls whether /join/apply accepts applications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment".
 */
export interface Recruitment {
  id: string;
  /**
   * Enforced server-side by /api/apply — anything but Open rejects submissions even when posted to directly.
   */
  status: 'open' | 'under-review' | 'closed';
  openingMessage?: string | null;
  closingDate?: string | null;
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /support campaign — its gate, its copy, and the accounts donors send to.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crowdfunding".
 */
export interface Crowdfunding {
  id: string;
  /**
   * Enforced server-side by /api/donate — a closed campaign rejects submissions even when posted to directly.
   */
  status: 'open' | 'paused' | 'closed';
  headline?: string | null;
  /**
   * Why the team needs support. Shown under the page hero.
   */
  pitch?: string | null;
  /**
   * Shown in place of the form when the campaign is not open.
   */
  closedMessage?: string | null;
  /**
   * Drives the "N days left" line on every support CTA. Passing it only stops the countdown — it does NOT close the campaign, so set the status too.
   */
  deadline?: string | null;
  /**
   * Sets the "we verify within N hours" promise shown to donors.
   */
  verificationHours?: number | null;
  /**
   * How many people contributed. Never a monetary figure — amounts are published nowhere on the site.
   */
  showSupporterCount?: boolean | null;
  /**
   * The receiving accounts donors copy from /support. PUBLIC by design — do not put a personal account here unless the team means it to be public.
   */
  channels?:
    | {
        method: 'bKash' | 'Nagad' | 'Rocket' | 'Upay' | 'Bank Transfer' | 'Other';
        accountType?: ('Personal' | 'Merchant' | 'Agent' | 'Current' | 'Savings') | null;
        /**
         * Exactly as the donor should type it into their app.
         */
        accountNumber: string;
        /**
         * So donors can confirm they are sending to the right place.
         */
        accountName?: string | null;
        note?: string | null;
        bankName?: string | null;
        branch?: string | null;
        routingNumber?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use the built-in four-step explanation.
   */
  steps?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use the built-in FAQ.
   */
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The shop gate, delivery, order limits and policies.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop".
 */
export interface Shop {
  id: string;
  /**
   * Enforced server-side by /api/shop/order — a paused or closed shop rejects orders even when posted to directly.
   */
  status: 'open' | 'paused' | 'closed';
  /**
   * Shown in place of the checkout button. Say when you expect to reopen.
   */
  closedMessage?: string | null;
  /**
   * Optional banner across the shop pages. Empty hides it.
   */
  announcement?: string | null;
  /**
   * Flat courier charge on home-delivery orders. Campus handover is always free and is not configurable.
   */
  standardDeliveryFee: number;
  /**
   * Turn off during holidays when nobody is on campus.
   */
  campusDeliveryEnabled?: boolean | null;
  /**
   * The pick-up spots offered at checkout. Empty lets the customer type their own.
   */
  campusHandoverPoints?: string[] | null;
  /**
   * OFF by design — free handover is open to anyone. Turn ON only if it starts being abused: it then requires a @bracu.ac.bd address, enforced server-side, and locks out alumni and guests.
   */
  requireBracuEmailForCampus?: boolean | null;
  /**
   * Free text shown at checkout and in the confirmation email.
   */
  estimatedDeliveryDays?: string | null;
  /**
   * Subtotal before delivery. 0 means no minimum.
   */
  minOrderValue: number;
  /**
   * Stops one person clearing out a size in a single order.
   */
  maxQtyPerItem: number;
  /**
   * Total units across the whole cart.
   */
  maxItemsPerOrder: number;
  /**
   * Leads every track ID, e.g. "MT" gives MT-7K4QX2ZP. Changing it does not rewrite IDs already issued — old ones keep working.
   */
  orderPrefix: string;
  /**
   * PUBLISHED — the reply-to shown to customers for order questions.
   */
  supportEmail?: string | null;
  /**
   * PUBLISHED — shown on the order confirmation.
   */
  supportPhone?: string | null;
  /**
   * NEVER PUBLISHED. Team inboxes alerted on each new order. Leave empty to disable alerts.
   */
  adminNotifyEmails?: string[] | null;
  /**
   * Shown in an accordion on every product page and at checkout.
   */
  shippingPolicy?: string | null;
  /**
   * Be explicit about what can be returned and by when — it prevents disputes.
   */
  returnPolicy?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment_select".
 */
export interface RecruitmentSelect<T extends boolean = true> {
  status?: T;
  openingMessage?: T;
  closingDate?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crowdfunding_select".
 */
export interface CrowdfundingSelect<T extends boolean = true> {
  status?: T;
  headline?: T;
  pitch?: T;
  closedMessage?: T;
  deadline?: T;
  verificationHours?: T;
  showSupporterCount?: T;
  channels?:
    | T
    | {
        method?: T;
        accountType?: T;
        accountNumber?: T;
        accountName?: T;
        note?: T;
        bankName?: T;
        branch?: T;
        routingNumber?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop_select".
 */
export interface ShopSelect<T extends boolean = true> {
  status?: T;
  closedMessage?: T;
  announcement?: T;
  standardDeliveryFee?: T;
  campusDeliveryEnabled?: T;
  campusHandoverPoints?: T;
  requireBracuEmailForCampus?: T;
  estimatedDeliveryDays?: T;
  minOrderValue?: T;
  maxQtyPerItem?: T;
  maxItemsPerOrder?: T;
  orderPrefix?: T;
  supportEmail?: T;
  supportPhone?: T;
  adminNotifyEmails?: T;
  shippingPolicy?: T;
  returnPolicy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}