/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    announcements: Announcement;
    posts: Post;
    research: Research;
    sponsors: Sponsor;
    members: Member;
    testimonials: Testimonial;
    rovers: Rover;
    competitions: Competition;
    'sar-videos': SarVideo;
    media: Media;
    documents: Document;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    research: ResearchSelect<false> | ResearchSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    rovers: RoversSelect<false> | RoversSelect<true>;
    competitions: CompetitionsSelect<false> | CompetitionsSelect<true>;
    'sar-videos': SarVideosSelect<false> | SarVideosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The strip across the top of every page. Only active, in-window rows show.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: string;
  /**
   * Internal label so you can tell rows apart. Never shown on the site.
   */
  title: string;
  /**
   * What visitors read. One short sentence — it has to fit on a phone.
   */
  message: string;
  /**
   * Optional. Makes the bar clickable.
   */
  link?: string | null;
  /**
   * The call to action, e.g. "Apply Now", "See Results".
   */
  linkLabel?: string | null;
  /**
   * Leave empty to start immediately.
   */
  startDate?: string | null;
  /**
   * Leave empty to run until switched off by hand.
   */
  endDate?: string | null;
  isActive?: boolean | null;
  /**
   * Lower numbers are shown first.
   */
  priority?: number | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everything on /news.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  /**
   * The URL for this page. Generated from the name if left empty. Changing it breaks any link already shared.
   */
  slug: string;
  title: string;
  publishedAt?: string | null;
  category: 'competition-update' | 'rover-reveal' | 'research-highlight' | 'outreach' | 'team-news';
  author?: (string | null) | Member;
  featuredImage?: (string | null) | Media;
  /**
   * The summary on cards and in link previews. Written to stand alone — it is often all anyone reads.
   */
  excerpt: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everyone who has worked on the team, current and alumni.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  /**
   * The URL for this page. Generated from the name if left empty. Changing it breaks any link already shared.
   */
  slug: string;
  name: string;
  /**
   * A square-ish headshot reads best.
   */
  photo?: (string | null) | Media;
  role?: string | null;
  /**
   * One short line under the name, e.g. "Autonomy & perception, building rovers that think."
   */
  tagline?: string | null;
  /**
   * Drives the badge colour and the filter on /team.
   */
  subTeam?:
    | ('uav' | 'rnd' | 'autonomous' | 'controls' | 'mechanical' | 'electronics' | 'science' | 'network' | 'management')
    | null;
  yearOfStudy?: string | null;
  joinedYear?: number | null;
  graduationYear?: number | null;
  /**
   * Every year this member was active, e.g. 2021, 2022, 2023. Drives the contribution timeline on their profile.
   */
  yearsContributed?: number[] | null;
  isAlumni?: boolean | null;
  /**
   * Where they work or study now.
   */
  currentOrg?: string | null;
  isActive?: boolean | null;
  /**
   * A few sentences on who they are and what they do here.
   */
  bio?: string | null;
  quote?: string | null;
  /**
   * What they specialise in — "Path planning", "PCB design", "Structural FEA".
   */
  focusAreas?: string[] | null;
  skills?: string[] | null;
  achievements?:
    | {
        /**
         * The award, role or milestone, e.g. "URC 2023 — 5th Worldwide".
         */
        title: string;
        year?: number | null;
        /**
         * One-line summary of what they achieved.
         */
        achievement?: string | null;
        /**
         * Optional bullet points elaborating on it.
         */
        details?: string[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Notable projects, repos or publications — a name and a link.
   */
  works?:
    | {
        name: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  linkedin?: string | null;
  github?: string | null;
  website?: string | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for screen readers and for when it fails to load. Not a caption — say what is in it.
   */
  alt: string;
  /**
   * Optional. Shown under the image in galleries. Sanity stored this on each usage; here it lives with the image, so one edit fixes it everywhere.
   */
  caption?: string | null;
  /**
   * Photographer or source, where one needs crediting.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    email?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Publications. Authors are team members, so profiles list them automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research".
 */
export interface Research {
  id: string;
  /**
   * The URL for this page. Generated from the name if left empty. Changing it breaks any link already shared.
   */
  slug: string;
  title: string;
  /**
   * In citation order. Each author’s profile links back to this paper.
   */
  authors?: (string | Member)[] | null;
  year: number;
  status: 'published' | 'preprint' | 'under-review';
  conference?: string | null;
  abstract: string;
  doi?: string | null;
  pdfFile?: (string | null) | Document;
  /**
   * Drives the filter on /research.
   */
  topics?: string[] | null;
  citation?: string | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  /**
   * What this file is, in words a person would search for — e.g. "Taurus SAR report 2024". Used as the download link label.
   */
  title: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Shown on /sponsors and in the strip across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: string;
  name: string;
  tier: 'title' | 'gold' | 'silver' | 'bronze' | 'in-kind';
  /**
   * The dark-mark version, which reads on white backgrounds.
   */
  logoLight?: (string | null) | Media;
  /**
   * The light-mark version, which reads on dark backgrounds.
   */
  logoDark?: (string | null) | Media;
  /**
   * Fallback for older entries. Prefer the two theme-specific logos above.
   */
  logo?: (string | null) | Media;
  website?: string | null;
  startYear?: number | null;
  isActive?: boolean | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Only featured testimonials are shown on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  role?: string | null;
  organization?: string | null;
  /**
   * Keep it punchy — one to three sentences.
   */
  quote: string;
  /**
   * A square-ish headshot reads best.
   */
  photo?: (string | null) | Media;
  /**
   * LinkedIn, faculty page or personal site. Makes the name clickable.
   */
  link?: string | null;
  /**
   * Off means invisible. Tick to publish it to Home and About.
   */
  featured?: boolean | null;
  /**
   * Lower shows first. Ties fall back to name.
   */
  order?: number | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The fleet. Mark exactly one as the current flagship.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rovers".
 */
export interface Rover {
  id: string;
  /**
   * The URL for this page. Generated from the name if left empty. Changing it breaks any link already shared.
   */
  slug: string;
  /**
   * The codename, e.g. "Taurus", "Hypersonic".
   */
  name: string;
  year: number;
  /**
   * The team’s current rover. Highlighted across the site.
   */
  isFlagship?: boolean | null;
  /**
   * A short product-style line, e.g. "The rover that learned to think on Martian terrain."
   */
  tagline?: string | null;
  /**
   * Two to four sentences on this rover and what made the build notable. Shown in the hero.
   */
  overview?: string | null;
  /**
   * Lead engineer for this build cycle.
   */
  teamLead?: string | null;
  /**
   * The competition this rover was built for, e.g. URC 2026.
   */
  competition?: (string | null) | Competition;
  /**
   * System Acceptance Review video. Paste the full watch or youtu.be link — it is embedded on the page.
   */
  sarVideoUrl?: string | null;
  /**
   * The hero shot. Falls back to the first gallery image when empty.
   */
  featuredImage?: (string | null) | Media;
  /**
   * Captions live on the image itself now (Media → Caption), so fixing one fixes it everywhere it appears.
   */
  gallery?: (string | Media)[] | null;
  diagrams?: (string | Media)[] | null;
  /**
   * Hotspots overlaid on the first diagram, positioned by percentage.
   */
  diagramAnnotations?:
    | {
        label: string;
        description?: string | null;
        xPercent: number;
        yPercent: number;
        id?: string | null;
      }[]
    | null;
  cadModel?: (string | null) | Document;
  technicalPdf?: (string | null) | Document;
  /**
   * The structured specs shown on the fleet cards.
   */
  specs?: {
    weight?: string | null;
    dimensions?: string | null;
    driveSystem?: string | null;
    payload?: string | null;
    dof?: number | null;
    autonomy?: string | null;
  };
  /**
   * Free-form telemetry for the detail page, e.g. "Comms Range" → "3.3 km NLoS".
   */
  keySpecs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Notable named hardware and software — "Jetson Orin", "ZED 2i", "ROS2 Humble", "YOLO11n".
   */
  namedComponents?: string[] | null;
  /**
   * The headline breakthroughs. Drives the feature reel on the page.
   */
  keyInnovations?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Mechanical, Controls & Software, Electronics, Network & Vision, Autonomy, Science. Each becomes a feature section.
   */
  subsystems?:
    | {
        name: string;
        /**
         * Colours the section accent and links it to a sub-team.
         */
        subTeam?:
          | (
              | 'uav'
              | 'rnd'
              | 'autonomous'
              | 'controls'
              | 'mechanical'
              | 'electronics'
              | 'science'
              | 'network'
              | 'management'
            )
          | null;
        summary: string;
        /**
         * Concrete bullets — named parts, numbers, techniques.
         */
        highlights?: string[] | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * How this rover tackles each competition mission — Delivery, Equipment Servicing, Autonomous Navigation, Science.
   */
  missions?:
    | {
        name: string;
        summary: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Who built this rover. Their sub-team drives the tab filter on the page.
   */
  crew?:
    | {
        member: string | Member;
        /**
         * What they worked on here, e.g. "Lead — manipulator & IK".
         */
        contribution?: string | null;
        /**
         * Only if their contribution to THIS rover differs from their primary sub-team. Otherwise the member’s own sub-team is used.
         */
        subTeamOverride?:
          | (
              | 'uav'
              | 'rnd'
              | 'autonomous'
              | 'controls'
              | 'mechanical'
              | 'electronics'
              | 'science'
              | 'network'
              | 'management'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every competition the team has entered, with its result and roster.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions".
 */
export interface Competition {
  id: string;
  /**
   * The URL for this page. Generated from the name if left empty. Changing it breaks any link already shared.
   */
  slug: string;
  name: string;
  shortName: string;
  year: number;
  location?: string | null;
  result?: string | null;
  rank?: number | null;
  totalTeams?: number | null;
  rover?: (string | null) | Rover;
  teamMembers?:
    | {
        member: string | Member;
        competitionRole?:
          | (
              | 'Driver'
              | 'Science Lead'
              | 'Systems Integrator'
              | 'Operator'
              | 'Arm Operator'
              | 'Autonomy Lead'
              | 'Team Lead'
              | 'Support'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  sarVideo?: string | null;
  gallery?: (string | Media)[] | null;
  reportPdf?: (string | null) | Document;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sar-videos".
 */
export interface SarVideo {
  id: string;
  title: string;
  competition: string | Competition;
  year: number;
  youtubeUrl: string;
  /**
   * Optional — YouTube’s own thumbnail is used when empty.
   */
  thumbnail?: (string | null) | Media;
  description?: string | null;
  legacySanityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Shown in the admin UI so changes are attributable to a person.
   */
  name: string;
  role: 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'announcements';
        value: string | Announcement;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'research';
        value: string | Research;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: string | Sponsor;
      } | null)
    | ({
        relationTo: 'members';
        value: string | Member;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'rovers';
        value: string | Rover;
      } | null)
    | ({
        relationTo: 'competitions';
        value: string | Competition;
      } | null)
    | ({
        relationTo: 'sar-videos';
        value: string | SarVideo;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  link?: T;
  linkLabel?: T;
  startDate?: T;
  endDate?: T;
  isActive?: T;
  priority?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  publishedAt?: T;
  category?: T;
  author?: T;
  featuredImage?: T;
  excerpt?: T;
  body?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_select".
 */
export interface ResearchSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  authors?: T;
  year?: T;
  status?: T;
  conference?: T;
  abstract?: T;
  doi?: T;
  pdfFile?: T;
  topics?: T;
  citation?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  tier?: T;
  logoLight?: T;
  logoDark?: T;
  logo?: T;
  website?: T;
  startYear?: T;
  isActive?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  photo?: T;
  role?: T;
  tagline?: T;
  subTeam?: T;
  yearOfStudy?: T;
  joinedYear?: T;
  graduationYear?: T;
  yearsContributed?: T;
  isAlumni?: T;
  currentOrg?: T;
  isActive?: T;
  bio?: T;
  quote?: T;
  focusAreas?: T;
  skills?: T;
  achievements?:
    | T
    | {
        title?: T;
        year?: T;
        achievement?: T;
        details?: T;
        id?: T;
      };
  works?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  linkedin?: T;
  github?: T;
  website?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  organization?: T;
  quote?: T;
  photo?: T;
  link?: T;
  featured?: T;
  order?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rovers_select".
 */
export interface RoversSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  year?: T;
  isFlagship?: T;
  tagline?: T;
  overview?: T;
  teamLead?: T;
  competition?: T;
  sarVideoUrl?: T;
  featuredImage?: T;
  gallery?: T;
  diagrams?: T;
  diagramAnnotations?:
    | T
    | {
        label?: T;
        description?: T;
        xPercent?: T;
        yPercent?: T;
        id?: T;
      };
  cadModel?: T;
  technicalPdf?: T;
  specs?:
    | T
    | {
        weight?: T;
        dimensions?: T;
        driveSystem?: T;
        payload?: T;
        dof?: T;
        autonomy?: T;
      };
  keySpecs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  namedComponents?: T;
  keyInnovations?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  subsystems?:
    | T
    | {
        name?: T;
        subTeam?: T;
        summary?: T;
        highlights?: T;
        image?: T;
        id?: T;
      };
  missions?:
    | T
    | {
        name?: T;
        summary?: T;
        id?: T;
      };
  crew?:
    | T
    | {
        member?: T;
        contribution?: T;
        subTeamOverride?: T;
        id?: T;
      };
  description?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions_select".
 */
export interface CompetitionsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  shortName?: T;
  year?: T;
  location?: T;
  result?: T;
  rank?: T;
  totalTeams?: T;
  rover?: T;
  teamMembers?:
    | T
    | {
        member?: T;
        competitionRole?: T;
        id?: T;
      };
  sarVideo?: T;
  gallery?: T;
  reportPdf?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sar-videos_select".
 */
export interface SarVideosSelect<T extends boolean = true> {
  title?: T;
  competition?: T;
  year?: T;
  youtubeUrl?: T;
  thumbnail?: T;
  description?: T;
  legacySanityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        email?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}